version: '3.8'

services:
  cryptomarket:
    build: .
    container_name: cryptomarket-app
    restart: unless-stopped
    ports:
      - "3001:3000"  # Map port 3001 on host to 3000 in container
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - cryptomarket-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Resource limits to prevent one app from affecting others
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

networks:
  cryptomarket-network:
    driver: bridge
    # Isolated network for crypto-market
    name: cryptomarket-network
